services:
  db:
    image: mysql:8.0
    env_file:
      - .env

    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql-data:/var/lib/mysql


  jokes-service:
    build: 
      context: ./jokes_microservice
      dockerfile: Dockerfile
    env_file:
      - .env

    ports:
      - "80:3000"
    restart: unless-stopped


  etl_service:
    build:
      context: ./etl_application
    env_file:
      - .env

    restart: unless-stopped  
    depends_on:
      - db

volumes:
  mysql-data:
