services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - jokes-network

  jokes-service:
    build: 
      context: ./jokes_microservice
      dockerfile: Dockerfile

    environment:
      - DB_HOST=microservicesassignment-db-1
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - jokes-network 

volumes:
  mysql-data:

networks:
  jokes-network: